//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CompanyOrgModel", "jednostka_organizacyjnauzytkownik", "jednostka_organizacyjna", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CompanyOrg.jednostka_organizacyjna), "uzytkownik", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CompanyOrg.uzytkownik), true)]
[assembly: EdmRelationshipAttribute("CompanyOrgModel", "lokalizacjauzytkownik", "lokalizacja", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CompanyOrg.lokalizacja), "uzytkownik", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CompanyOrg.uzytkownik), true)]
[assembly: EdmRelationshipAttribute("CompanyOrgModel", "komputerlokalizacja", "komputer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CompanyOrg.komputer), "lokalizacja", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CompanyOrg.lokalizacja), true)]
[assembly: EdmRelationshipAttribute("CompanyOrgModel", "komputeruzytkownik", "komputer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CompanyOrg.komputer), "uzytkownik", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CompanyOrg.uzytkownik), true)]

#endregion

namespace CompanyOrg
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CompanyOrgEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CompanyOrgEntities object using the connection string found in the 'CompanyOrgEntities' section of the application configuration file.
        /// </summary>
        public CompanyOrgEntities() : base("name=CompanyOrgEntities", "CompanyOrgEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CompanyOrgEntities object.
        /// </summary>
        public CompanyOrgEntities(string connectionString) : base(connectionString, "CompanyOrgEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CompanyOrgEntities object.
        /// </summary>
        public CompanyOrgEntities(EntityConnection connection) : base(connection, "CompanyOrgEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<jednostka_organizacyjna> jednostka_organizacyjna
        {
            get
            {
                if ((_jednostka_organizacyjna == null))
                {
                    _jednostka_organizacyjna = base.CreateObjectSet<jednostka_organizacyjna>("jednostka_organizacyjna");
                }
                return _jednostka_organizacyjna;
            }
        }
        private ObjectSet<jednostka_organizacyjna> _jednostka_organizacyjna;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<komputer> komputer
        {
            get
            {
                if ((_komputer == null))
                {
                    _komputer = base.CreateObjectSet<komputer>("komputer");
                }
                return _komputer;
            }
        }
        private ObjectSet<komputer> _komputer;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<lokalizacja> lokalizacja
        {
            get
            {
                if ((_lokalizacja == null))
                {
                    _lokalizacja = base.CreateObjectSet<lokalizacja>("lokalizacja");
                }
                return _lokalizacja;
            }
        }
        private ObjectSet<lokalizacja> _lokalizacja;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<uzytkownik> uzytkownik
        {
            get
            {
                if ((_uzytkownik == null))
                {
                    _uzytkownik = base.CreateObjectSet<uzytkownik>("uzytkownik");
                }
                return _uzytkownik;
            }
        }
        private ObjectSet<uzytkownik> _uzytkownik;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the jednostka_organizacyjna EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTojednostka_organizacyjna(jednostka_organizacyjna jednostka_organizacyjna)
        {
            base.AddObject("jednostka_organizacyjna", jednostka_organizacyjna);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the komputer EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTokomputer(komputer komputer)
        {
            base.AddObject("komputer", komputer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the lokalizacja EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTolokalizacja(lokalizacja lokalizacja)
        {
            base.AddObject("lokalizacja", lokalizacja);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the uzytkownik EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouzytkownik(uzytkownik uzytkownik)
        {
            base.AddObject("uzytkownik", uzytkownik);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CompanyOrgModel", Name="jednostka_organizacyjna")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class jednostka_organizacyjna : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new jednostka_organizacyjna object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nazwa">Initial value of the nazwa property.</param>
        /// <param name="kod">Initial value of the kod property.</param>
        /// <param name="status">Initial value of the status property.</param>
        /// <param name="id_manager">Initial value of the id_manager property.</param>
        /// <param name="id_nadrzedna">Initial value of the id_nadrzedna property.</param>
        public static jednostka_organizacyjna Createjednostka_organizacyjna(global::System.Int32 id, global::System.String nazwa, global::System.String kod, global::System.Boolean status, global::System.Int32 id_manager, global::System.Int32 id_nadrzedna)
        {
            jednostka_organizacyjna jednostka_organizacyjna = new jednostka_organizacyjna();
            jednostka_organizacyjna.Id = id;
            jednostka_organizacyjna.nazwa = nazwa;
            jednostka_organizacyjna.kod = kod;
            jednostka_organizacyjna.status = status;
            jednostka_organizacyjna.id_manager = id_manager;
            jednostka_organizacyjna.id_nadrzedna = id_nadrzedna;
            return jednostka_organizacyjna;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nazwa
        {
            get
            {
                return _nazwa;
            }
            set
            {
                OnnazwaChanging(value);
                ReportPropertyChanging("nazwa");
                _nazwa = StructuralObject.SetValidValue(value, false, "nazwa");
                ReportPropertyChanged("nazwa");
                OnnazwaChanged();
            }
        }
        private global::System.String _nazwa;
        partial void OnnazwaChanging(global::System.String value);
        partial void OnnazwaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String kod
        {
            get
            {
                return _kod;
            }
            set
            {
                OnkodChanging(value);
                ReportPropertyChanging("kod");
                _kod = StructuralObject.SetValidValue(value, false, "kod");
                ReportPropertyChanged("kod");
                OnkodChanged();
            }
        }
        private global::System.String _kod;
        partial void OnkodChanging(global::System.String value);
        partial void OnkodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, "status");
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.Boolean _status;
        partial void OnstatusChanging(global::System.Boolean value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_manager
        {
            get
            {
                return _id_manager;
            }
            set
            {
                Onid_managerChanging(value);
                ReportPropertyChanging("id_manager");
                _id_manager = StructuralObject.SetValidValue(value, "id_manager");
                ReportPropertyChanged("id_manager");
                Onid_managerChanged();
            }
        }
        private global::System.Int32 _id_manager;
        partial void Onid_managerChanging(global::System.Int32 value);
        partial void Onid_managerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MPK
        {
            get
            {
                return _MPK;
            }
            set
            {
                OnMPKChanging(value);
                ReportPropertyChanging("MPK");
                _MPK = StructuralObject.SetValidValue(value, true, "MPK");
                ReportPropertyChanged("MPK");
                OnMPKChanged();
            }
        }
        private global::System.String _MPK;
        partial void OnMPKChanging(global::System.String value);
        partial void OnMPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_nadrzedna
        {
            get
            {
                return _id_nadrzedna;
            }
            set
            {
                Onid_nadrzednaChanging(value);
                ReportPropertyChanging("id_nadrzedna");
                _id_nadrzedna = StructuralObject.SetValidValue(value, "id_nadrzedna");
                ReportPropertyChanged("id_nadrzedna");
                Onid_nadrzednaChanged();
            }
        }
        private global::System.Int32 _id_nadrzedna;
        partial void Onid_nadrzednaChanging(global::System.Int32 value);
        partial void Onid_nadrzednaChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CompanyOrgModel", "jednostka_organizacyjnauzytkownik", "uzytkownik")]
        public EntityCollection<uzytkownik> uzytkownik
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<uzytkownik>("CompanyOrgModel.jednostka_organizacyjnauzytkownik", "uzytkownik");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<uzytkownik>("CompanyOrgModel.jednostka_organizacyjnauzytkownik", "uzytkownik", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CompanyOrgModel", Name="komputer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class komputer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new komputer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nazwa">Initial value of the nazwa property.</param>
        /// <param name="nazwa_dns">Initial value of the nazwa_dns property.</param>
        /// <param name="numer_seryjny">Initial value of the numer_seryjny property.</param>
        /// <param name="host_name">Initial value of the host_name property.</param>
        /// <param name="nr_inwentarzowy">Initial value of the nr_inwentarzowy property.</param>
        /// <param name="typ_komputera">Initial value of the typ_komputera property.</param>
        /// <param name="adres_ip">Initial value of the adres_ip property.</param>
        /// <param name="rozmiar_hdd">Initial value of the rozmiar_hdd property.</param>
        /// <param name="nazwa_monitora">Initial value of the nazwa_monitora property.</param>
        /// <param name="model_procesora">Initial value of the model_procesora property.</param>
        /// <param name="lokalizacjaId">Initial value of the lokalizacjaId property.</param>
        /// <param name="wlascicielID">Initial value of the wlascicielID property.</param>
        public static komputer Createkomputer(global::System.Int32 id, global::System.String nazwa, global::System.String nazwa_dns, global::System.String numer_seryjny, global::System.String host_name, global::System.String nr_inwentarzowy, global::System.Int32 typ_komputera, global::System.String adres_ip, global::System.String rozmiar_hdd, global::System.String nazwa_monitora, global::System.Int32 model_procesora, global::System.Int32 lokalizacjaId, global::System.Int32 wlascicielID)
        {
            komputer komputer = new komputer();
            komputer.Id = id;
            komputer.nazwa = nazwa;
            komputer.nazwa_dns = nazwa_dns;
            komputer.numer_seryjny = numer_seryjny;
            komputer.host_name = host_name;
            komputer.nr_inwentarzowy = nr_inwentarzowy;
            komputer.typ_komputera = typ_komputera;
            komputer.adres_ip = adres_ip;
            komputer.rozmiar_hdd = rozmiar_hdd;
            komputer.nazwa_monitora = nazwa_monitora;
            komputer.model_procesora = model_procesora;
            komputer.lokalizacjaId = lokalizacjaId;
            komputer.wlascicielID = wlascicielID;
            return komputer;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nazwa
        {
            get
            {
                return _nazwa;
            }
            set
            {
                OnnazwaChanging(value);
                ReportPropertyChanging("nazwa");
                _nazwa = StructuralObject.SetValidValue(value, false, "nazwa");
                ReportPropertyChanged("nazwa");
                OnnazwaChanged();
            }
        }
        private global::System.String _nazwa;
        partial void OnnazwaChanging(global::System.String value);
        partial void OnnazwaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nazwa_dns
        {
            get
            {
                return _nazwa_dns;
            }
            set
            {
                Onnazwa_dnsChanging(value);
                ReportPropertyChanging("nazwa_dns");
                _nazwa_dns = StructuralObject.SetValidValue(value, false, "nazwa_dns");
                ReportPropertyChanged("nazwa_dns");
                Onnazwa_dnsChanged();
            }
        }
        private global::System.String _nazwa_dns;
        partial void Onnazwa_dnsChanging(global::System.String value);
        partial void Onnazwa_dnsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String numer_seryjny
        {
            get
            {
                return _numer_seryjny;
            }
            set
            {
                Onnumer_seryjnyChanging(value);
                ReportPropertyChanging("numer_seryjny");
                _numer_seryjny = StructuralObject.SetValidValue(value, false, "numer_seryjny");
                ReportPropertyChanged("numer_seryjny");
                Onnumer_seryjnyChanged();
            }
        }
        private global::System.String _numer_seryjny;
        partial void Onnumer_seryjnyChanging(global::System.String value);
        partial void Onnumer_seryjnyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String host_name
        {
            get
            {
                return _host_name;
            }
            set
            {
                Onhost_nameChanging(value);
                ReportPropertyChanging("host_name");
                _host_name = StructuralObject.SetValidValue(value, false, "host_name");
                ReportPropertyChanged("host_name");
                Onhost_nameChanged();
            }
        }
        private global::System.String _host_name;
        partial void Onhost_nameChanging(global::System.String value);
        partial void Onhost_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MPK
        {
            get
            {
                return _MPK;
            }
            set
            {
                OnMPKChanging(value);
                ReportPropertyChanging("MPK");
                _MPK = StructuralObject.SetValidValue(value, true, "MPK");
                ReportPropertyChanged("MPK");
                OnMPKChanged();
            }
        }
        private global::System.String _MPK;
        partial void OnMPKChanging(global::System.String value);
        partial void OnMPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String szczegoly_lokalizacji
        {
            get
            {
                return _szczegoly_lokalizacji;
            }
            set
            {
                Onszczegoly_lokalizacjiChanging(value);
                ReportPropertyChanging("szczegoly_lokalizacji");
                _szczegoly_lokalizacji = StructuralObject.SetValidValue(value, true, "szczegoly_lokalizacji");
                ReportPropertyChanged("szczegoly_lokalizacji");
                Onszczegoly_lokalizacjiChanged();
            }
        }
        private global::System.String _szczegoly_lokalizacji;
        partial void Onszczegoly_lokalizacjiChanging(global::System.String value);
        partial void Onszczegoly_lokalizacjiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nr_inwentarzowy
        {
            get
            {
                return _nr_inwentarzowy;
            }
            set
            {
                Onnr_inwentarzowyChanging(value);
                ReportPropertyChanging("nr_inwentarzowy");
                _nr_inwentarzowy = StructuralObject.SetValidValue(value, false, "nr_inwentarzowy");
                ReportPropertyChanged("nr_inwentarzowy");
                Onnr_inwentarzowyChanged();
            }
        }
        private global::System.String _nr_inwentarzowy;
        partial void Onnr_inwentarzowyChanging(global::System.String value);
        partial void Onnr_inwentarzowyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String wartosc_poczatkowa
        {
            get
            {
                return _wartosc_poczatkowa;
            }
            set
            {
                Onwartosc_poczatkowaChanging(value);
                ReportPropertyChanging("wartosc_poczatkowa");
                _wartosc_poczatkowa = StructuralObject.SetValidValue(value, true, "wartosc_poczatkowa");
                ReportPropertyChanged("wartosc_poczatkowa");
                Onwartosc_poczatkowaChanged();
            }
        }
        private global::System.String _wartosc_poczatkowa;
        partial void Onwartosc_poczatkowaChanging(global::System.String value);
        partial void Onwartosc_poczatkowaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String wartosc_netto
        {
            get
            {
                return _wartosc_netto;
            }
            set
            {
                Onwartosc_nettoChanging(value);
                ReportPropertyChanging("wartosc_netto");
                _wartosc_netto = StructuralObject.SetValidValue(value, true, "wartosc_netto");
                ReportPropertyChanged("wartosc_netto");
                Onwartosc_nettoChanged();
            }
        }
        private global::System.String _wartosc_netto;
        partial void Onwartosc_nettoChanging(global::System.String value);
        partial void Onwartosc_nettoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numer_ot
        {
            get
            {
                return _numer_ot;
            }
            set
            {
                Onnumer_otChanging(value);
                ReportPropertyChanging("numer_ot");
                _numer_ot = StructuralObject.SetValidValue(value, true, "numer_ot");
                ReportPropertyChanged("numer_ot");
                Onnumer_otChanged();
            }
        }
        private global::System.String _numer_ot;
        partial void Onnumer_otChanging(global::System.String value);
        partial void Onnumer_otChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 typ_komputera
        {
            get
            {
                return _typ_komputera;
            }
            set
            {
                Ontyp_komputeraChanging(value);
                ReportPropertyChanging("typ_komputera");
                _typ_komputera = StructuralObject.SetValidValue(value, "typ_komputera");
                ReportPropertyChanged("typ_komputera");
                Ontyp_komputeraChanged();
            }
        }
        private global::System.Int32 _typ_komputera;
        partial void Ontyp_komputeraChanging(global::System.Int32 value);
        partial void Ontyp_komputeraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nr_id_system_zew
        {
            get
            {
                return _nr_id_system_zew;
            }
            set
            {
                Onnr_id_system_zewChanging(value);
                ReportPropertyChanging("nr_id_system_zew");
                _nr_id_system_zew = StructuralObject.SetValidValue(value, true, "nr_id_system_zew");
                ReportPropertyChanged("nr_id_system_zew");
                Onnr_id_system_zewChanged();
            }
        }
        private global::System.String _nr_id_system_zew;
        partial void Onnr_id_system_zewChanging(global::System.String value);
        partial void Onnr_id_system_zewChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> cd_dvd
        {
            get
            {
                return _cd_dvd;
            }
            set
            {
                Oncd_dvdChanging(value);
                ReportPropertyChanging("cd_dvd");
                _cd_dvd = StructuralObject.SetValidValue(value, "cd_dvd");
                ReportPropertyChanged("cd_dvd");
                Oncd_dvdChanged();
            }
        }
        private Nullable<global::System.Boolean> _cd_dvd;
        partial void Oncd_dvdChanging(Nullable<global::System.Boolean> value);
        partial void Oncd_dvdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> karta_sieciowa
        {
            get
            {
                return _karta_sieciowa;
            }
            set
            {
                Onkarta_sieciowaChanging(value);
                ReportPropertyChanging("karta_sieciowa");
                _karta_sieciowa = StructuralObject.SetValidValue(value, "karta_sieciowa");
                ReportPropertyChanged("karta_sieciowa");
                Onkarta_sieciowaChanged();
            }
        }
        private Nullable<global::System.Boolean> _karta_sieciowa;
        partial void Onkarta_sieciowaChanging(Nullable<global::System.Boolean> value);
        partial void Onkarta_sieciowaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String adres_ip
        {
            get
            {
                return _adres_ip;
            }
            set
            {
                Onadres_ipChanging(value);
                ReportPropertyChanging("adres_ip");
                _adres_ip = StructuralObject.SetValidValue(value, false, "adres_ip");
                ReportPropertyChanged("adres_ip");
                Onadres_ipChanged();
            }
        }
        private global::System.String _adres_ip;
        partial void Onadres_ipChanging(global::System.String value);
        partial void Onadres_ipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String zegar_cpu
        {
            get
            {
                return _zegar_cpu;
            }
            set
            {
                Onzegar_cpuChanging(value);
                ReportPropertyChanging("zegar_cpu");
                _zegar_cpu = StructuralObject.SetValidValue(value, true, "zegar_cpu");
                ReportPropertyChanged("zegar_cpu");
                Onzegar_cpuChanged();
            }
        }
        private global::System.String _zegar_cpu;
        partial void Onzegar_cpuChanging(global::System.String value);
        partial void Onzegar_cpuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ilosc_proc
        {
            get
            {
                return _ilosc_proc;
            }
            set
            {
                Onilosc_procChanging(value);
                ReportPropertyChanging("ilosc_proc");
                _ilosc_proc = StructuralObject.SetValidValue(value, "ilosc_proc");
                ReportPropertyChanged("ilosc_proc");
                Onilosc_procChanged();
            }
        }
        private Nullable<global::System.Int32> _ilosc_proc = 1;
        partial void Onilosc_procChanging(Nullable<global::System.Int32> value);
        partial void Onilosc_procChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ilosc_ram
        {
            get
            {
                return _ilosc_ram;
            }
            set
            {
                Onilosc_ramChanging(value);
                ReportPropertyChanging("ilosc_ram");
                _ilosc_ram = StructuralObject.SetValidValue(value, "ilosc_ram");
                ReportPropertyChanged("ilosc_ram");
                Onilosc_ramChanged();
            }
        }
        private Nullable<global::System.Int32> _ilosc_ram;
        partial void Onilosc_ramChanging(Nullable<global::System.Int32> value);
        partial void Onilosc_ramChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rozmiar_hdd
        {
            get
            {
                return _rozmiar_hdd;
            }
            set
            {
                Onrozmiar_hddChanging(value);
                ReportPropertyChanging("rozmiar_hdd");
                _rozmiar_hdd = StructuralObject.SetValidValue(value, false, "rozmiar_hdd");
                ReportPropertyChanged("rozmiar_hdd");
                Onrozmiar_hddChanged();
            }
        }
        private global::System.String _rozmiar_hdd;
        partial void Onrozmiar_hddChanging(global::System.String value);
        partial void Onrozmiar_hddChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rozmiar_monitora
        {
            get
            {
                return _rozmiar_monitora;
            }
            set
            {
                Onrozmiar_monitoraChanging(value);
                ReportPropertyChanging("rozmiar_monitora");
                _rozmiar_monitora = StructuralObject.SetValidValue(value, true, "rozmiar_monitora");
                ReportPropertyChanged("rozmiar_monitora");
                Onrozmiar_monitoraChanged();
            }
        }
        private global::System.String _rozmiar_monitora;
        partial void Onrozmiar_monitoraChanging(global::System.String value);
        partial void Onrozmiar_monitoraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nazwa_monitora
        {
            get
            {
                return _nazwa_monitora;
            }
            set
            {
                Onnazwa_monitoraChanging(value);
                ReportPropertyChanging("nazwa_monitora");
                _nazwa_monitora = StructuralObject.SetValidValue(value, false, "nazwa_monitora");
                ReportPropertyChanged("nazwa_monitora");
                Onnazwa_monitoraChanged();
            }
        }
        private global::System.String _nazwa_monitora;
        partial void Onnazwa_monitoraChanging(global::System.String value);
        partial void Onnazwa_monitoraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 model_procesora
        {
            get
            {
                return _model_procesora;
            }
            set
            {
                Onmodel_procesoraChanging(value);
                ReportPropertyChanging("model_procesora");
                _model_procesora = StructuralObject.SetValidValue(value, "model_procesora");
                ReportPropertyChanged("model_procesora");
                Onmodel_procesoraChanged();
            }
        }
        private global::System.Int32 _model_procesora;
        partial void Onmodel_procesoraChanging(global::System.Int32 value);
        partial void Onmodel_procesoraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String model_komputera
        {
            get
            {
                return _model_komputera;
            }
            set
            {
                Onmodel_komputeraChanging(value);
                ReportPropertyChanging("model_komputera");
                _model_komputera = StructuralObject.SetValidValue(value, true, "model_komputera");
                ReportPropertyChanged("model_komputera");
                Onmodel_komputeraChanged();
            }
        }
        private global::System.String _model_komputera;
        partial void Onmodel_komputeraChanging(global::System.String value);
        partial void Onmodel_komputeraChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 lokalizacjaId
        {
            get
            {
                return _lokalizacjaId;
            }
            set
            {
                OnlokalizacjaIdChanging(value);
                ReportPropertyChanging("lokalizacjaId");
                _lokalizacjaId = StructuralObject.SetValidValue(value, "lokalizacjaId");
                ReportPropertyChanged("lokalizacjaId");
                OnlokalizacjaIdChanged();
            }
        }
        private global::System.Int32 _lokalizacjaId;
        partial void OnlokalizacjaIdChanging(global::System.Int32 value);
        partial void OnlokalizacjaIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 wlascicielID
        {
            get
            {
                return _wlascicielID;
            }
            set
            {
                OnwlascicielIDChanging(value);
                ReportPropertyChanging("wlascicielID");
                _wlascicielID = StructuralObject.SetValidValue(value, "wlascicielID");
                ReportPropertyChanged("wlascicielID");
                OnwlascicielIDChanged();
            }
        }
        private global::System.Int32 _wlascicielID;
        partial void OnwlascicielIDChanging(global::System.Int32 value);
        partial void OnwlascicielIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CompanyOrgModel", "komputerlokalizacja", "lokalizacja")]
        public lokalizacja lokalizacja
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lokalizacja>("CompanyOrgModel.komputerlokalizacja", "lokalizacja").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lokalizacja>("CompanyOrgModel.komputerlokalizacja", "lokalizacja").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<lokalizacja> lokalizacjaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lokalizacja>("CompanyOrgModel.komputerlokalizacja", "lokalizacja");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<lokalizacja>("CompanyOrgModel.komputerlokalizacja", "lokalizacja", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CompanyOrgModel", "komputeruzytkownik", "uzytkownik")]
        public uzytkownik uzytkownik
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<uzytkownik>("CompanyOrgModel.komputeruzytkownik", "uzytkownik").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<uzytkownik>("CompanyOrgModel.komputeruzytkownik", "uzytkownik").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<uzytkownik> uzytkownikReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<uzytkownik>("CompanyOrgModel.komputeruzytkownik", "uzytkownik");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<uzytkownik>("CompanyOrgModel.komputeruzytkownik", "uzytkownik", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CompanyOrgModel", Name="lokalizacja")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class lokalizacja : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new lokalizacja object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="miasto">Initial value of the miasto property.</param>
        public static lokalizacja Createlokalizacja(global::System.Int32 id, global::System.String miasto)
        {
            lokalizacja lokalizacja = new lokalizacja();
            lokalizacja.Id = id;
            lokalizacja.miasto = miasto;
            return lokalizacja;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ulica
        {
            get
            {
                return _ulica;
            }
            set
            {
                OnulicaChanging(value);
                ReportPropertyChanging("ulica");
                _ulica = StructuralObject.SetValidValue(value, true, "ulica");
                ReportPropertyChanged("ulica");
                OnulicaChanged();
            }
        }
        private global::System.String _ulica;
        partial void OnulicaChanging(global::System.String value);
        partial void OnulicaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String miasto
        {
            get
            {
                return _miasto;
            }
            set
            {
                OnmiastoChanging(value);
                ReportPropertyChanging("miasto");
                _miasto = StructuralObject.SetValidValue(value, false, "miasto");
                ReportPropertyChanged("miasto");
                OnmiastoChanged();
            }
        }
        private global::System.String _miasto;
        partial void OnmiastoChanging(global::System.String value);
        partial void OnmiastoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String kod_pocztowy
        {
            get
            {
                return _kod_pocztowy;
            }
            set
            {
                Onkod_pocztowyChanging(value);
                ReportPropertyChanging("kod_pocztowy");
                _kod_pocztowy = StructuralObject.SetValidValue(value, true, "kod_pocztowy");
                ReportPropertyChanged("kod_pocztowy");
                Onkod_pocztowyChanged();
            }
        }
        private global::System.String _kod_pocztowy;
        partial void Onkod_pocztowyChanging(global::System.String value);
        partial void Onkod_pocztowyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pokoj
        {
            get
            {
                return _pokoj;
            }
            set
            {
                OnpokojChanging(value);
                ReportPropertyChanging("pokoj");
                _pokoj = StructuralObject.SetValidValue(value, true, "pokoj");
                ReportPropertyChanged("pokoj");
                OnpokojChanged();
            }
        }
        private global::System.String _pokoj;
        partial void OnpokojChanging(global::System.String value);
        partial void OnpokojChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CompanyOrgModel", "lokalizacjauzytkownik", "uzytkownik")]
        public EntityCollection<uzytkownik> uzytkownik
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<uzytkownik>("CompanyOrgModel.lokalizacjauzytkownik", "uzytkownik");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<uzytkownik>("CompanyOrgModel.lokalizacjauzytkownik", "uzytkownik", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CompanyOrgModel", "komputerlokalizacja", "komputer")]
        public EntityCollection<komputer> komputer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<komputer>("CompanyOrgModel.komputerlokalizacja", "komputer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<komputer>("CompanyOrgModel.komputerlokalizacja", "komputer", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CompanyOrgModel", Name="uzytkownik")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class uzytkownik : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new uzytkownik object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nazwisko">Initial value of the nazwisko property.</param>
        /// <param name="imie">Initial value of the imie property.</param>
        /// <param name="nRE">Initial value of the NRE property.</param>
        /// <param name="status">Initial value of the status property.</param>
        /// <param name="login_AD">Initial value of the login_AD property.</param>
        /// <param name="typ_kontaktu">Initial value of the typ_kontaktu property.</param>
        /// <param name="typ_dostepu">Initial value of the typ_dostepu property.</param>
        /// <param name="jednostka_organizacyjnaID_JO">Initial value of the jednostka_organizacyjnaID_JO property.</param>
        /// <param name="lokalizacjaId">Initial value of the lokalizacjaId property.</param>
        public static uzytkownik Createuzytkownik(global::System.Int32 id, global::System.String nazwisko, global::System.String imie, global::System.String nRE, global::System.Boolean status, global::System.String login_AD, global::System.Int32 typ_kontaktu, global::System.Int32 typ_dostepu, global::System.Int32 jednostka_organizacyjnaID_JO, global::System.Int32 lokalizacjaId)
        {
            uzytkownik uzytkownik = new uzytkownik();
            uzytkownik.Id = id;
            uzytkownik.nazwisko = nazwisko;
            uzytkownik.imie = imie;
            uzytkownik.NRE = nRE;
            uzytkownik.status = status;
            uzytkownik.login_AD = login_AD;
            uzytkownik.typ_kontaktu = typ_kontaktu;
            uzytkownik.typ_dostepu = typ_dostepu;
            uzytkownik.jednostka_organizacyjnaID_JO = jednostka_organizacyjnaID_JO;
            uzytkownik.lokalizacjaId = lokalizacjaId;
            return uzytkownik;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nazwisko
        {
            get
            {
                return _nazwisko;
            }
            set
            {
                OnnazwiskoChanging(value);
                ReportPropertyChanging("nazwisko");
                _nazwisko = StructuralObject.SetValidValue(value, false, "nazwisko");
                ReportPropertyChanged("nazwisko");
                OnnazwiskoChanged();
            }
        }
        private global::System.String _nazwisko;
        partial void OnnazwiskoChanging(global::System.String value);
        partial void OnnazwiskoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String imie
        {
            get
            {
                return _imie;
            }
            set
            {
                OnimieChanging(value);
                ReportPropertyChanging("imie");
                _imie = StructuralObject.SetValidValue(value, false, "imie");
                ReportPropertyChanged("imie");
                OnimieChanged();
            }
        }
        private global::System.String _imie;
        partial void OnimieChanging(global::System.String value);
        partial void OnimieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NRE
        {
            get
            {
                return _NRE;
            }
            set
            {
                OnNREChanging(value);
                ReportPropertyChanging("NRE");
                _NRE = StructuralObject.SetValidValue(value, false, "NRE");
                ReportPropertyChanged("NRE");
                OnNREChanged();
            }
        }
        private global::System.String _NRE;
        partial void OnNREChanging(global::System.String value);
        partial void OnNREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String drugie_imie
        {
            get
            {
                return _drugie_imie;
            }
            set
            {
                Ondrugie_imieChanging(value);
                ReportPropertyChanging("drugie_imie");
                _drugie_imie = StructuralObject.SetValidValue(value, true, "drugie_imie");
                ReportPropertyChanged("drugie_imie");
                Ondrugie_imieChanged();
            }
        }
        private global::System.String _drugie_imie;
        partial void Ondrugie_imieChanging(global::System.String value);
        partial void Ondrugie_imieChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, "status");
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.Boolean _status;
        partial void OnstatusChanging(global::System.Boolean value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String login_AD
        {
            get
            {
                return _login_AD;
            }
            set
            {
                Onlogin_ADChanging(value);
                ReportPropertyChanging("login_AD");
                _login_AD = StructuralObject.SetValidValue(value, false, "login_AD");
                ReportPropertyChanged("login_AD");
                Onlogin_ADChanged();
            }
        }
        private global::System.String _login_AD;
        partial void Onlogin_ADChanging(global::System.String value);
        partial void Onlogin_ADChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 typ_kontaktu
        {
            get
            {
                return _typ_kontaktu;
            }
            set
            {
                Ontyp_kontaktuChanging(value);
                ReportPropertyChanging("typ_kontaktu");
                _typ_kontaktu = StructuralObject.SetValidValue(value, "typ_kontaktu");
                ReportPropertyChanged("typ_kontaktu");
                Ontyp_kontaktuChanged();
            }
        }
        private global::System.Int32 _typ_kontaktu;
        partial void Ontyp_kontaktuChanging(global::System.Int32 value);
        partial void Ontyp_kontaktuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 typ_dostepu
        {
            get
            {
                return _typ_dostepu;
            }
            set
            {
                Ontyp_dostepuChanging(value);
                ReportPropertyChanging("typ_dostepu");
                _typ_dostepu = StructuralObject.SetValidValue(value, "typ_dostepu");
                ReportPropertyChanged("typ_dostepu");
                Ontyp_dostepuChanged();
            }
        }
        private global::System.Int32 _typ_dostepu;
        partial void Ontyp_dostepuChanging(global::System.Int32 value);
        partial void Ontyp_dostepuChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> stanowisko
        {
            get
            {
                return _stanowisko;
            }
            set
            {
                OnstanowiskoChanging(value);
                ReportPropertyChanging("stanowisko");
                _stanowisko = StructuralObject.SetValidValue(value, "stanowisko");
                ReportPropertyChanged("stanowisko");
                OnstanowiskoChanged();
            }
        }
        private Nullable<global::System.Int32> _stanowisko;
        partial void OnstanowiskoChanging(Nullable<global::System.Int32> value);
        partial void OnstanowiskoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> AWiZ
        {
            get
            {
                return _AWiZ;
            }
            set
            {
                OnAWiZChanging(value);
                ReportPropertyChanging("AWiZ");
                _AWiZ = StructuralObject.SetValidValue(value, "AWiZ");
                ReportPropertyChanged("AWiZ");
                OnAWiZChanged();
            }
        }
        private Nullable<global::System.Boolean> _AWiZ;
        partial void OnAWiZChanging(Nullable<global::System.Boolean> value);
        partial void OnAWiZChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> delegacja_akceptacji
        {
            get
            {
                return _delegacja_akceptacji;
            }
            set
            {
                Ondelegacja_akceptacjiChanging(value);
                ReportPropertyChanging("delegacja_akceptacji");
                _delegacja_akceptacji = StructuralObject.SetValidValue(value, "delegacja_akceptacji");
                ReportPropertyChanged("delegacja_akceptacji");
                Ondelegacja_akceptacjiChanged();
            }
        }
        private Nullable<global::System.Int32> _delegacja_akceptacji;
        partial void Ondelegacja_akceptacjiChanging(Nullable<global::System.Int32> value);
        partial void Ondelegacja_akceptacjiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tel_kom
        {
            get
            {
                return _tel_kom;
            }
            set
            {
                Ontel_komChanging(value);
                ReportPropertyChanging("tel_kom");
                _tel_kom = StructuralObject.SetValidValue(value, true, "tel_kom");
                ReportPropertyChanged("tel_kom");
                Ontel_komChanged();
            }
        }
        private global::System.String _tel_kom;
        partial void Ontel_komChanging(global::System.String value);
        partial void Ontel_komChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String tel_stac
        {
            get
            {
                return _tel_stac;
            }
            set
            {
                Ontel_stacChanging(value);
                ReportPropertyChanging("tel_stac");
                _tel_stac = StructuralObject.SetValidValue(value, true, "tel_stac");
                ReportPropertyChanged("tel_stac");
                Ontel_stacChanged();
            }
        }
        private global::System.String _tel_stac;
        partial void Ontel_stacChanging(global::System.String value);
        partial void Ontel_stacChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MPK
        {
            get
            {
                return _MPK;
            }
            set
            {
                OnMPKChanging(value);
                ReportPropertyChanging("MPK");
                _MPK = StructuralObject.SetValidValue(value, true, "MPK");
                ReportPropertyChanged("MPK");
                OnMPKChanged();
            }
        }
        private global::System.String _MPK;
        partial void OnMPKChanging(global::System.String value);
        partial void OnMPKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 jednostka_organizacyjnaID_JO
        {
            get
            {
                return _jednostka_organizacyjnaID_JO;
            }
            set
            {
                Onjednostka_organizacyjnaID_JOChanging(value);
                ReportPropertyChanging("jednostka_organizacyjnaID_JO");
                _jednostka_organizacyjnaID_JO = StructuralObject.SetValidValue(value, "jednostka_organizacyjnaID_JO");
                ReportPropertyChanged("jednostka_organizacyjnaID_JO");
                Onjednostka_organizacyjnaID_JOChanged();
            }
        }
        private global::System.Int32 _jednostka_organizacyjnaID_JO;
        partial void Onjednostka_organizacyjnaID_JOChanging(global::System.Int32 value);
        partial void Onjednostka_organizacyjnaID_JOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 lokalizacjaId
        {
            get
            {
                return _lokalizacjaId;
            }
            set
            {
                OnlokalizacjaIdChanging(value);
                ReportPropertyChanging("lokalizacjaId");
                _lokalizacjaId = StructuralObject.SetValidValue(value, "lokalizacjaId");
                ReportPropertyChanged("lokalizacjaId");
                OnlokalizacjaIdChanged();
            }
        }
        private global::System.Int32 _lokalizacjaId;
        partial void OnlokalizacjaIdChanging(global::System.Int32 value);
        partial void OnlokalizacjaIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CompanyOrgModel", "jednostka_organizacyjnauzytkownik", "jednostka_organizacyjna")]
        public jednostka_organizacyjna jednostka_organizacyjna
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<jednostka_organizacyjna>("CompanyOrgModel.jednostka_organizacyjnauzytkownik", "jednostka_organizacyjna").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<jednostka_organizacyjna>("CompanyOrgModel.jednostka_organizacyjnauzytkownik", "jednostka_organizacyjna").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<jednostka_organizacyjna> jednostka_organizacyjnaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<jednostka_organizacyjna>("CompanyOrgModel.jednostka_organizacyjnauzytkownik", "jednostka_organizacyjna");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<jednostka_organizacyjna>("CompanyOrgModel.jednostka_organizacyjnauzytkownik", "jednostka_organizacyjna", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CompanyOrgModel", "lokalizacjauzytkownik", "lokalizacja")]
        public lokalizacja lokalizacja
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lokalizacja>("CompanyOrgModel.lokalizacjauzytkownik", "lokalizacja").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lokalizacja>("CompanyOrgModel.lokalizacjauzytkownik", "lokalizacja").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<lokalizacja> lokalizacjaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<lokalizacja>("CompanyOrgModel.lokalizacjauzytkownik", "lokalizacja");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<lokalizacja>("CompanyOrgModel.lokalizacjauzytkownik", "lokalizacja", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CompanyOrgModel", "komputeruzytkownik", "komputer")]
        public EntityCollection<komputer> komputer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<komputer>("CompanyOrgModel.komputeruzytkownik", "komputer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<komputer>("CompanyOrgModel.komputeruzytkownik", "komputer", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
